# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-01 14:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('description', models.TextField(blank=True, verbose_name='\u63cf\u8ff0')),
                ('take_time', models.IntegerField(verbose_name='\u9700\u8981\u65f6\u95f4')),
                ('auditor', models.ManyToManyField(related_name='workorder_auditor', to=settings.AUTH_USER_MODEL, verbose_name='\u5ba1\u6279\u4eba')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
                ('operator', models.ManyToManyField(related_name='workorder_operator', to=settings.AUTH_USER_MODEL, verbose_name='\u6267\u884c\u4eba')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u6807\u51c6\u5de5\u5355',
                'verbose_name_plural': '\u6807\u51c6\u5de5\u5355',
            },
        ),
    ]
