# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-02 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFM06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, verbose_name='\u5de5\u4ee3')),
                ('department', models.CharField(max_length=50, verbose_name='\u90e8\u9580')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u62ac\u982d',
                'verbose_name_plural': '\u62ac\u982d',
            },
        ),
        migrations.CreateModel(
            name='ERequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u65e5\u671f')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u6b21\u66f4\u65b0')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('status', models.CharField(choices=[(b'0', b'\xe5\xb7\xb2\xe6\x8f\x90\xe4\xba\xa4'), (b'1', b'\xe5\xae\xa1\xe6\x89\xb9\xe4\xb8\xad'), (b'2', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'3', b'\xe5\xb7\xb2\xe5\xa4\x84\xe7\x90\x86'), (b'4', b'\xe5\xb7\xb2\xe7\xa1\xae\xe8\xae\xa4'), (b'5', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=5, verbose_name='\u72b6\u6001')),
                ('efmid', models.CharField(max_length=10, verbose_name='\u7de8\u865f')),
                ('opinion01', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c101')),
                ('opinion02', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c102')),
                ('opinion03', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c103')),
                ('opinion04', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c104')),
                ('act_01', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u6001')),
                ('act_02', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u6001')),
                ('act_03', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u6001')),
                ('act_04', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u6001')),
                ('rep_time_01', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f401')),
                ('rep_time_02', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f402')),
                ('rep_time_03', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f403')),
                ('rep_time_04', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f404')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('expire_time', models.DateTimeField(verbose_name='\u671f\u671b\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
                ('efm06', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eforms.EFM06', verbose_name=b'\xe8\xb2\xbb\xe7\x94\xa8\xe5\xa0\xb1\xe9\x8a\xb7\xe5\x96\xae')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubEFM06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id_efm06', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='\u6458\u8981')),
                ('cost', models.FloatField(default=0.0)),
                ('proof', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u660e\u7d30',
                'verbose_name_plural': '\u660e\u7d30',
            },
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='operator',
        ),
        migrations.DeleteModel(
            name='Workorder',
        ),
    ]
