# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-03 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0002_auto_20171002_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subefm06',
            name='parent_id_efm06',
        ),
        migrations.AddField(
            model_name='subefm06',
            name='efm06',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eforms.EFM06', verbose_name=b'\xe8\xb2\xbb\xe7\x94\xa8\xe5\xa0\xb1\xe9\x8a\xb7\xe5\x96\xae'),
        ),
    ]
