# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-03 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0003_auto_20171003_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erequest',
            options={'ordering': ['id'], 'verbose_name': '\u7533\u8acb\u8acb\u6c42', 'verbose_name_plural': '\u7533\u8acb\u8acb\u6c42'},
        ),
    ]
