# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-03 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0004_auto_20171003_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erequest',
            name='act_01',
            field=models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600101'),
        ),
        migrations.AlterField(
            model_name='erequest',
            name='act_02',
            field=models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600102'),
        ),
        migrations.AlterField(
            model_name='erequest',
            name='act_03',
            field=models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600103'),
        ),
        migrations.AlterField(
            model_name='erequest',
            name='act_04',
            field=models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600104'),
        ),
        migrations.AlterField(
            model_name='erequest',
            name='efm06',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eforms.EFM06', verbose_name='\u8cbb\u7528\u5831\u92b7\u55ae'),
        ),
        migrations.AlterField(
            model_name='subefm06',
            name='efm06',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eforms.EFM06', verbose_name='\u8cbb\u7528\u5831\u92b7\u55ae'),
        ),
    ]
