# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0005_auto_20171003_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFM03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=50, verbose_name='\u5de5\u4ee3')),
                ('department', models.CharField(max_length=50, verbose_name='\u90e8\u9580')),
                ('adv_paydate', models.DateTimeField(verbose_name='\u4ed8\u6b3e\u65e5\u671f')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='\u59d3\u540d/\u516c\u53f8\u540d\u7a31')),
                ('receiver_account', models.CharField(max_length=50, verbose_name='\u5e33\u865f')),
                ('receiver_bank', models.CharField(max_length=50, verbose_name='\u958b\u6236\u884c\u5730\u5740')),
                ('adv_payment', models.CharField(max_length=50, verbose_name='\u8acb\u6b3e\u91d1\u984d')),
                ('purpose', models.CharField(choices=[(b'0', b'\xe8\xb2\xa8\xe6\xac\xbe'), (b'1', b'\xe5\xae\x9a\xe9\x87\x91'), (b'2', b'\xe5\x85\xb6\xe4\xbb\x96')], default='0', max_length=2, verbose_name='\u7528\u9014')),
                ('method', models.CharField(choices=[(b'0', b'\xe7\x8f\xbe\xe9\x87\x91'), (b'1', b'\xe8\xbd\x89\xe5\xb8\xb3/\xe9\x9b\xbb\xe5\x8c\xaf'), (b'2', b'\xe6\x94\xaf\xe7\xa5\xa8')], default='0', max_length=2, verbose_name='\u4ed8\u6b3e\u65b9\u5f0f')),
                ('unknown_01', models.CharField(max_length=50, verbose_name='\u6b78\u9084\u91d1\u984d')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u8acb\u6b3e\u55ae',
                'verbose_name_plural': '\u8acb\u6b3e\u55ae',
            },
        ),
    ]
