# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0006_efm03'),
    ]

    operations = [
        migrations.AddField(
            model_name='erequest',
            name='efm03',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='eforms.EFM03', verbose_name='\u8acb\u6b3e\u55ae'),
            preserve_default=False,
        ),
    ]
