# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-03 13:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eforms', '0007_erequest_efm03'),
    ]

    operations = [
        migrations.CreateModel(
            name='EFMRequest03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('project_code', models.CharField(max_length=50, verbose_name='\u5de5\u4ee3')),
                ('department', models.CharField(max_length=50, verbose_name='\u90e8\u9580')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u65e5\u671f')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u6b21\u66f4\u65b0')),
                ('adv_paydate', models.DateTimeField(verbose_name='\u4ed8\u6b3e\u65e5\u671f')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='\u59d3\u540d/\u516c\u53f8\u540d\u7a31')),
                ('receiver_account', models.CharField(max_length=50, verbose_name='\u5e33\u865f')),
                ('receiver_bank', models.CharField(max_length=50, verbose_name='\u958b\u6236\u884c\u5730\u5740')),
                ('adv_payment', models.CharField(max_length=50, verbose_name='\u8acb\u6b3e\u91d1\u984d')),
                ('purpose', models.CharField(choices=[(b'0', b'\xe8\xb2\xa8\xe6\xac\xbe'), (b'1', b'\xe5\xae\x9a\xe9\x87\x91'), (b'2', b'\xe5\x85\xb6\xe4\xbb\x96')], default='0', max_length=2, verbose_name='\u7528\u9014')),
                ('method', models.CharField(choices=[(b'0', b'\xe7\x8f\xbe\xe9\x87\x91'), (b'1', b'\xe8\xbd\x89\xe5\xb8\xb3/\xe9\x9b\xbb\xe5\x8c\xaf'), (b'2', b'\xe6\x94\xaf\xe7\xa5\xa8')], default='0', max_length=2, verbose_name='\u4ed8\u6b3e\u65b9\u5f0f')),
                ('unknown_01', models.CharField(max_length=50, verbose_name='\u5be6\u6536\u91d1\u984d')),
                ('unknown_02', models.CharField(max_length=50, verbose_name='\u5831\u92b7\u65e5\u671f')),
                ('unknown_03', models.CharField(max_length=50, verbose_name='\u5831\u92b7\u62b5\u92b7\u91d1\u984d')),
                ('unknown_04', models.CharField(max_length=50, verbose_name='\u6b78\u9084\u91d1\u984d')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u8acb\u6b3e\u55ae',
                'verbose_name_plural': '\u8acb\u6b3e\u55ae',
            },
        ),
        migrations.CreateModel(
            name='EFMRequest06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('project_code', models.CharField(max_length=50, verbose_name='\u5de5\u4ee3')),
                ('department', models.CharField(max_length=50, verbose_name='\u90e8\u9580')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u65e5\u671f')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='\u4e0a\u6b21\u66f4\u65b0')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u8005')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u62ac\u982d',
                'verbose_name_plural': '\u62ac\u982d',
            },
        ),
        migrations.CreateModel(
            name='EReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('description', models.TextField(verbose_name='\u63cf\u8ff0')),
                ('status', models.CharField(choices=[(b'0', b'\xe5\xb7\xb2\xe6\x8f\x90\xe4\xba\xa4'), (b'1', b'\xe5\xae\xa1\xe6\x89\xb9\xe4\xb8\xad'), (b'2', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'3', b'\xe5\xb7\xb2\xe5\xa4\x84\xe7\x90\x86'), (b'4', b'\xe5\xb7\xb2\xe7\xa1\xae\xe8\xae\xa4'), (b'5', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=5, verbose_name='\u72b6\u6001')),
                ('opinion_01', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c101')),
                ('opinion_02', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c102')),
                ('opinion_03', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c103')),
                ('opinion_04', models.TextField(blank=True, max_length=100, verbose_name='\u5ba1\u6279\u610f\u89c104')),
                ('act_01', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600101')),
                ('act_02', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600102')),
                ('act_03', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600103')),
                ('act_04', models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600104')),
                ('rep_time_01', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f401')),
                ('rep_time_02', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f402')),
                ('rep_time_03', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f403')),
                ('rep_time_04', models.DateTimeField(verbose_name='\u56de\u8986\u65f6\u95f404')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('expire_time', models.DateTimeField(verbose_name='\u671f\u671b\u65f6\u95f4')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u5be9\u67e5',
                'verbose_name_plural': '\u5be9\u67e5',
            },
        ),
        migrations.RemoveField(
            model_name='erequest',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='erequest',
            name='efm03',
        ),
        migrations.RemoveField(
            model_name='erequest',
            name='efm06',
        ),
        migrations.AlterField(
            model_name='subefm06',
            name='efm06',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eforms.EFMRequest06', verbose_name='\u8cbb\u7528\u5831\u92b7\u55ae'),
        ),
        migrations.DeleteModel(
            name='EFM03',
        ),
        migrations.DeleteModel(
            name='EFM06',
        ),
        migrations.DeleteModel(
            name='ERequest',
        ),
        migrations.AddField(
            model_name='efmrequest06',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eforms.EReview', verbose_name='\u5be9\u67e5'),
        ),
        migrations.AddField(
            model_name='efmrequest03',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eforms.EReview', verbose_name='\u5be9\u67e5'),
        ),
    ]
