# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-04 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0010_auto_20171004_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efmrequest03',
            name='adv_paydate',
            field=models.DateTimeField(error_messages={'required': '\u4e0d\u5f97\u70ba\u7a7a'}, verbose_name='\u4ed8\u6b3e\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='adv_payment',
            field=models.CharField(error_messages={'required': '\u4e0d\u5f97\u70ba\u7a7a'}, max_length=50, verbose_name='\u8acb\u6b3e\u91d1\u984d'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='project_code',
            field=models.TextField(error_messages={'required': '\u4e0d\u5f97\u70ba\u7a7a'}, max_length=50, verbose_name='\u5de5\u4ee3'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='receiver_account',
            field=models.TextField(error_messages={'required': '\u4e0d\u5f97\u70ba\u7a7a'}, max_length=50, verbose_name='\u5e33\u865f'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='receiver_bank',
            field=models.TextField(error_messages={'required': '\u4e0d\u5f97\u70ba\u7a7a'}, max_length=100, verbose_name='\u958b\u6236\u884c\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='receiver_name',
            field=models.TextField(error_messages={'required': '\u4e0d\u5f97\u70ba\u7a7a'}, max_length=50, verbose_name='\u59d3\u540d/\u516c\u53f8\u540d\u7a31'),
        ),
    ]
