# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-04 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0012_auto_20171004_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ereview',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='expire_time',
            field=models.DateTimeField(blank=True, verbose_name='\u671f\u671b\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_01',
            field=models.DateTimeField(blank=True, verbose_name='\u56de\u8986\u65f6\u95f401'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_02',
            field=models.DateTimeField(blank=True, verbose_name='\u56de\u8986\u65f6\u95f402'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_03',
            field=models.DateTimeField(blank=True, verbose_name='\u56de\u8986\u65f6\u95f403'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_04',
            field=models.DateTimeField(blank=True, verbose_name='\u56de\u8986\u65f6\u95f404'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='title',
            field=models.TextField(blank=True, max_length=30, verbose_name='\u6807\u9898'),
        ),
    ]
