# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-04 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0013_auto_20171004_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ereview',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u671f\u671b\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='finish_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='opinion_01',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5ba1\u6279\u610f\u89c101'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='opinion_02',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5ba1\u6279\u610f\u89c102'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='opinion_03',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5ba1\u6279\u610f\u89c103'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='opinion_04',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5ba1\u6279\u610f\u89c104'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_01',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u56de\u8986\u65f6\u95f401'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_02',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u56de\u8986\u65f6\u95f402'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_03',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u56de\u8986\u65f6\u95f403'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='rep_time_04',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u56de\u8986\u65f6\u95f404'),
        ),
        migrations.AlterField(
            model_name='ereview',
            name='title',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='\u6807\u9898'),
        ),
    ]
