# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-04 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0014_auto_20171004_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efmrequest03',
            name='adv_paydate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u4ed8\u6b3e\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='department',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='\u90e8\u9580'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='title',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='unknown_01',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5be6\u6536\u91d1\u984d'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='unknown_02',
            field=models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='\u5831\u92b7\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='unknown_03',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5831\u92b7\u62b5\u92b7\u91d1\u984d'),
        ),
        migrations.AlterField(
            model_name='efmrequest03',
            name='unknown_04',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u6b78\u9084\u91d1\u984d'),
        ),
    ]
