# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-04 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0015_auto_20171004_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='efmrequest03',
            name='code',
            field=models.CharField(default=2, max_length=50, verbose_name='uid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='efmrequest06',
            name='code',
            field=models.CharField(default=3, max_length=50, verbose_name='uid'),
            preserve_default=False,
        ),
    ]
