# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-05 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0016_auto_20171004_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efmrequest03',
            name='code',
        ),
        migrations.RemoveField(
            model_name='efmrequest06',
            name='code',
        ),
    ]
