# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-05 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eforms', '0017_auto_20171005_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ereview',
            name='act_05',
            field=models.CharField(choices=[(b'0', b'\xe8\x99\x95\xe7\x90\x86\xe4\xb8\xad'), (b'1', b'\xe5\xb7\xb2\xe5\xae\xa1\xe6\x89\xb9'), (b'2', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d')], default='0', max_length=2, verbose_name='\u72b6\u600105'),
        ),
        migrations.AddField(
            model_name='ereview',
            name='opinion_05',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='\u6703\u8a08\u610f\u89c104'),
        ),
        migrations.AddField(
            model_name='ereview',
            name='rep_time_05',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u56de\u8986\u65f6\u95f405'),
        ),
    ]
